[project]
name = "automated-finances"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "psycopg2>=2.9.10",
    "sqlalchemy>=2.0.38",
    "streamlit>=1.43.1",
    "plotly>=5.19.0",
]
